apiVersion: v1
kind: Pod
metadata:
  name: nginx.example.com
  labels:
    app: hellonginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - name: nginx-port
      containerPort: 80
